name: reddit
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ethicnology/dart-reddit

environment:
  sdk: ^3.1.0

dependencies:
  oauth2: ^2.0.2

dev_dependencies:
  dotenv: ^4.1.0
  lints: ^2.0.0
  test: ^1.21.0
